
// /project-root
// |-- /src
// |   |-- /admin           # Admin panel specific code
// |   |   |-- /controllers
// |   |   |-- /services
// |   |   |-- /models
// |   |   |-- /middlewares
// |   |   |-- /dto
// |   |   |-- /views       # Admin panel views (if using server-side rendering)
// |   |-- /website         # Website specific code
// |   |   |-- /controllers
// |   |   |-- /services
// |   |   |-- /models
// |   |   |-- /middlewares
// |   |   |-- /dto
// |   |   |-- /views       # Website views (if using server-side rendering)
// |   |-- /common          # Shared code between admin and website
// |   |   |-- /utils
// |   |   |-- /interfaces
// |   |   |-- /constants
// |   |-- /config          # Configuration files
// |   |-- /tests           # Unit and integration tests
// |   |-- app.module.ts    # Main application module (for NestJS)
// |   |-- main.ts          # Entry point of the application
// |-- /dist                # Compiled output (generated by TypeScript)
// |-- /node_modules        # Node.js modules
// |-- .env                 # Environment variables
// |-- .gitignore           # Git ignore file
// |-- package.json         # NPM package file
// |-- tsconfig.json        # TypeScript configuration
// |-- README.md            # Project documentation